// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Animal;
@class Animal_Builder;
typedef enum {
  Animal_VERSION_CURRENTVer1 = 100,
  Animal_VERSION_CURRENTVer2 = 200,
} Animal_VERSION_CURRENT;

BOOL Animal_VERSION_CURRENTIsValidValue(Animal_VERSION_CURRENT value);


@interface AnimalRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Animal : PBGeneratedMessage {
@private
  BOOL hasABool_:1;
  BOOL hasADouble_:1;
  BOOL hasAFloat_:1;
  BOOL hasAInt64_:1;
  BOOL hasAUint64_:1;
  BOOL hasAInt32_:1;
  BOOL hasAFixed64_:1;
  BOOL hasAFixed32_:1;
  BOOL hasAString_:1;
  BOOL hasABytes_:1;
  BOOL hasAUint32_:1;
  BOOL hasType_:1;
  BOOL hasASfixed32_:1;
  BOOL hasASfixed64_:1;
  BOOL hasASint32_:1;
  BOOL hasASint64_:1;
  BOOL aBool_:1;
  Float64 aDouble;
  Float32 aFloat;
  int64_t aInt64;
  int64_t aUint64;
  int32_t aInt32;
  int64_t aFixed64;
  int32_t aFixed32;
  NSString* aString;
  NSData* aBytes;
  int32_t aUint32;
  Animal_VERSION_CURRENT type;
  int32_t aSfixed32;
  int64_t aSfixed64;
  int32_t aSint32;
  int64_t aSint64;
}
- (BOOL) hasADouble;
- (BOOL) hasAFloat;
- (BOOL) hasAInt32;
- (BOOL) hasAInt64;
- (BOOL) hasAUint32;
- (BOOL) hasAUint64;
- (BOOL) hasASint32;
- (BOOL) hasASint64;
- (BOOL) hasAFixed32;
- (BOOL) hasAFixed64;
- (BOOL) hasASfixed32;
- (BOOL) hasASfixed64;
- (BOOL) hasABool;
- (BOOL) hasAString;
- (BOOL) hasABytes;
- (BOOL) hasType;
@property (readonly) Float64 aDouble;
@property (readonly) Float32 aFloat;
@property (readonly) int32_t aInt32;
@property (readonly) int64_t aInt64;
@property (readonly) int32_t aUint32;
@property (readonly) int64_t aUint64;
@property (readonly) int32_t aSint32;
@property (readonly) int64_t aSint64;
@property (readonly) int32_t aFixed32;
@property (readonly) int64_t aFixed64;
@property (readonly) int32_t aSfixed32;
@property (readonly) int64_t aSfixed64;
- (BOOL) aBool;
@property (readonly, retain) NSString* aString;
@property (readonly, retain) NSData* aBytes;
@property (readonly) Animal_VERSION_CURRENT type;

+ (Animal*) defaultInstance;
- (Animal*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Animal_Builder*) builder;
+ (Animal_Builder*) builder;
+ (Animal_Builder*) builderWithPrototype:(Animal*) prototype;

+ (Animal*) parseFromData:(NSData*) data;
+ (Animal*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Animal*) parseFromInputStream:(NSInputStream*) input;
+ (Animal*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Animal*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Animal*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Animal*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Animal_Builder : PBGeneratedMessage_Builder {
@private
  Animal* result;
}

- (Animal*) defaultInstance;

- (Animal_Builder*) clear;
- (Animal_Builder*) clone;

- (Animal*) build;
- (Animal*) buildPartial;

- (Animal_Builder*) mergeFrom:(Animal*) other;
- (Animal_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Animal_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasADouble;
- (Float64) aDouble;
- (Animal_Builder*) setADouble:(Float64) value;
- (Animal_Builder*) clearADouble;

- (BOOL) hasAFloat;
- (Float32) aFloat;
- (Animal_Builder*) setAFloat:(Float32) value;
- (Animal_Builder*) clearAFloat;

- (BOOL) hasAInt32;
- (int32_t) aInt32;
- (Animal_Builder*) setAInt32:(int32_t) value;
- (Animal_Builder*) clearAInt32;

- (BOOL) hasAInt64;
- (int64_t) aInt64;
- (Animal_Builder*) setAInt64:(int64_t) value;
- (Animal_Builder*) clearAInt64;

- (BOOL) hasAUint32;
- (int32_t) aUint32;
- (Animal_Builder*) setAUint32:(int32_t) value;
- (Animal_Builder*) clearAUint32;

- (BOOL) hasAUint64;
- (int64_t) aUint64;
- (Animal_Builder*) setAUint64:(int64_t) value;
- (Animal_Builder*) clearAUint64;

- (BOOL) hasASint32;
- (int32_t) aSint32;
- (Animal_Builder*) setASint32:(int32_t) value;
- (Animal_Builder*) clearASint32;

- (BOOL) hasASint64;
- (int64_t) aSint64;
- (Animal_Builder*) setASint64:(int64_t) value;
- (Animal_Builder*) clearASint64;

- (BOOL) hasAFixed32;
- (int32_t) aFixed32;
- (Animal_Builder*) setAFixed32:(int32_t) value;
- (Animal_Builder*) clearAFixed32;

- (BOOL) hasAFixed64;
- (int64_t) aFixed64;
- (Animal_Builder*) setAFixed64:(int64_t) value;
- (Animal_Builder*) clearAFixed64;

- (BOOL) hasASfixed32;
- (int32_t) aSfixed32;
- (Animal_Builder*) setASfixed32:(int32_t) value;
- (Animal_Builder*) clearASfixed32;

- (BOOL) hasASfixed64;
- (int64_t) aSfixed64;
- (Animal_Builder*) setASfixed64:(int64_t) value;
- (Animal_Builder*) clearASfixed64;

- (BOOL) hasABool;
- (BOOL) aBool;
- (Animal_Builder*) setABool:(BOOL) value;
- (Animal_Builder*) clearABool;

- (BOOL) hasAString;
- (NSString*) aString;
- (Animal_Builder*) setAString:(NSString*) value;
- (Animal_Builder*) clearAString;

- (BOOL) hasABytes;
- (NSData*) aBytes;
- (Animal_Builder*) setABytes:(NSData*) value;
- (Animal_Builder*) clearABytes;

- (BOOL) hasType;
- (Animal_VERSION_CURRENT) type;
- (Animal_Builder*) setType:(Animal_VERSION_CURRENT) value;
- (Animal_Builder*) clearType;
@end

