// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Cat;
@class Cat_Builder;
@class Dog;
@class Dog_Builder;
@class ExtensAnimal;
@class ExtensAnimal_Builder;

@interface ExtensAnimalRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ExtensAnimal : PBExtendableMessage {
@private
  BOOL hasName_:1;
  NSString* name;
}
- (BOOL) hasName;
@property (readonly, retain) NSString* name;

+ (ExtensAnimal*) defaultInstance;
- (ExtensAnimal*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ExtensAnimal_Builder*) builder;
+ (ExtensAnimal_Builder*) builder;
+ (ExtensAnimal_Builder*) builderWithPrototype:(ExtensAnimal*) prototype;

+ (ExtensAnimal*) parseFromData:(NSData*) data;
+ (ExtensAnimal*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ExtensAnimal*) parseFromInputStream:(NSInputStream*) input;
+ (ExtensAnimal*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ExtensAnimal*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ExtensAnimal*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ExtensAnimal*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ExtensAnimal_Builder : PBExtendableMessage_Builder {
@private
  ExtensAnimal* result;
}

- (ExtensAnimal*) defaultInstance;

- (ExtensAnimal_Builder*) clear;
- (ExtensAnimal_Builder*) clone;

- (ExtensAnimal*) build;
- (ExtensAnimal*) buildPartial;

- (ExtensAnimal_Builder*) mergeFrom:(ExtensAnimal*) other;
- (ExtensAnimal_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ExtensAnimal_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (ExtensAnimal_Builder*) setName:(NSString*) value;
- (ExtensAnimal_Builder*) clearName;
@end

@interface Cat : PBGeneratedMessage {
@private
  BOOL hasDeclawed_:1;
  int32_t declawed;
}
- (BOOL) hasDeclawed;
@property (readonly) int32_t declawed;

+ (Cat*) defaultInstance;
- (Cat*) defaultInstance;

+ (id<PBExtensionField>) animalCat;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Cat_Builder*) builder;
+ (Cat_Builder*) builder;
+ (Cat_Builder*) builderWithPrototype:(Cat*) prototype;

+ (Cat*) parseFromData:(NSData*) data;
+ (Cat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Cat*) parseFromInputStream:(NSInputStream*) input;
+ (Cat*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Cat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Cat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Cat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Cat_Builder : PBGeneratedMessage_Builder {
@private
  Cat* result;
}

- (Cat*) defaultInstance;

- (Cat_Builder*) clear;
- (Cat_Builder*) clone;

- (Cat*) build;
- (Cat*) buildPartial;

- (Cat_Builder*) mergeFrom:(Cat*) other;
- (Cat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Cat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDeclawed;
- (int32_t) declawed;
- (Cat_Builder*) setDeclawed:(int32_t) value;
- (Cat_Builder*) clearDeclawed;
@end

@interface Dog : PBGeneratedMessage {
@private
  BOOL hasBonesBuried_:1;
  int32_t bonesBuried;
}
- (BOOL) hasBonesBuried;
@property (readonly) int32_t bonesBuried;

+ (Dog*) defaultInstance;
- (Dog*) defaultInstance;

+ (id<PBExtensionField>) animalDog;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Dog_Builder*) builder;
+ (Dog_Builder*) builder;
+ (Dog_Builder*) builderWithPrototype:(Dog*) prototype;

+ (Dog*) parseFromData:(NSData*) data;
+ (Dog*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Dog*) parseFromInputStream:(NSInputStream*) input;
+ (Dog*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Dog*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Dog*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Dog*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Dog_Builder : PBGeneratedMessage_Builder {
@private
  Dog* result;
}

- (Dog*) defaultInstance;

- (Dog_Builder*) clear;
- (Dog_Builder*) clone;

- (Dog*) build;
- (Dog*) buildPartial;

- (Dog_Builder*) mergeFrom:(Dog*) other;
- (Dog_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Dog_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBonesBuried;
- (int32_t) bonesBuried;
- (Dog_Builder*) setBonesBuried:(int32_t) value;
- (Dog_Builder*) clearBonesBuried;
@end

