// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class BaseType;
@class BaseType_Builder;

@interface ExtensBaseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
+ (id<PBExtensionField>) price;
@end

@interface BaseType : PBExtendableMessage {
@private
  BOOL hasName_:1;
  BOOL hasQuantity_:1;
  NSString* name;
  int32_t quantity;
}
- (BOOL) hasName;
- (BOOL) hasQuantity;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t quantity;

+ (BaseType*) defaultInstance;
- (BaseType*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BaseType_Builder*) builder;
+ (BaseType_Builder*) builder;
+ (BaseType_Builder*) builderWithPrototype:(BaseType*) prototype;

+ (BaseType*) parseFromData:(NSData*) data;
+ (BaseType*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BaseType*) parseFromInputStream:(NSInputStream*) input;
+ (BaseType*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (BaseType*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BaseType*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BaseType*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BaseType_Builder : PBExtendableMessage_Builder {
@private
  BaseType* result;
}

- (BaseType*) defaultInstance;

- (BaseType_Builder*) clear;
- (BaseType_Builder*) clone;

- (BaseType*) build;
- (BaseType*) buildPartial;

- (BaseType_Builder*) mergeFrom:(BaseType*) other;
- (BaseType_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BaseType_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (BaseType_Builder*) setName:(NSString*) value;
- (BaseType_Builder*) clearName;

- (BOOL) hasQuantity;
- (int32_t) quantity;
- (BaseType_Builder*) setQuantity:(int32_t) value;
- (BaseType_Builder*) clearQuantity;
@end

