// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Message.pb.h"

@implementation MessageRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [MessageRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface OneMessage ()
@property (retain) NSString* name;
@property (retain) NSString* descript;
@property (retain) OneMessage_Received* receipt;
@end

@implementation OneMessage

- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) value {
  hasName_ = !!value;
}
@synthesize name;
- (BOOL) hasDescript {
  return !!hasDescript_;
}
- (void) setHasDescript:(BOOL) value {
  hasDescript_ = !!value;
}
@synthesize descript;
- (BOOL) hasReceipt {
  return !!hasReceipt_;
}
- (void) setHasReceipt:(BOOL) value {
  hasReceipt_ = !!value;
}
@synthesize receipt;
- (void) dealloc {
  self.name = nil;
  self.descript = nil;
  self.receipt = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.name = @"";
    self.descript = @"";
    self.receipt = [OneMessage_Received defaultInstance];
  }
  return self;
}
static OneMessage* defaultOneMessageInstance = nil;
+ (void) initialize {
  if (self == [OneMessage class]) {
    defaultOneMessageInstance = [[OneMessage alloc] init];
  }
}
+ (OneMessage*) defaultInstance {
  return defaultOneMessageInstance;
}
- (OneMessage*) defaultInstance {
  return defaultOneMessageInstance;
}
- (BOOL) isInitialized {
  if (!self.hasName) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasName) {
    [output writeString:1 value:self.name];
  }
  if (self.hasDescript) {
    [output writeString:2 value:self.descript];
  }
  if (self.hasReceipt) {
    [output writeMessage:3 value:self.receipt];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasName) {
    size += computeStringSize(1, self.name);
  }
  if (self.hasDescript) {
    size += computeStringSize(2, self.descript);
  }
  if (self.hasReceipt) {
    size += computeMessageSize(3, self.receipt);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (OneMessage*) parseFromData:(NSData*) data {
  return (OneMessage*)[[[OneMessage builder] mergeFromData:data] build];
}
+ (OneMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (OneMessage*)[[[OneMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (OneMessage*) parseFromInputStream:(NSInputStream*) input {
  return (OneMessage*)[[[OneMessage builder] mergeFromInputStream:input] build];
}
+ (OneMessage*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (OneMessage*)[[[OneMessage builder] mergeDelimitedFromInputStream:input] build];
}
+ (OneMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (OneMessage*)[[[OneMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (OneMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (OneMessage*)[[[OneMessage builder] mergeFromCodedInputStream:input] build];
}
+ (OneMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (OneMessage*)[[[OneMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (OneMessage_Builder*) builder {
  return [[[OneMessage_Builder alloc] init] autorelease];
}
+ (OneMessage_Builder*) builderWithPrototype:(OneMessage*) prototype {
  return [[OneMessage builder] mergeFrom:prototype];
}
- (OneMessage_Builder*) builder {
  return [OneMessage builder];
}
@end

@interface OneMessage_Received ()
@property (retain) NSString* title;
@property (retain) NSString* descript;
@end

@implementation OneMessage_Received

- (BOOL) hasTitle {
  return !!hasTitle_;
}
- (void) setHasTitle:(BOOL) value {
  hasTitle_ = !!value;
}
@synthesize title;
- (BOOL) hasDescript {
  return !!hasDescript_;
}
- (void) setHasDescript:(BOOL) value {
  hasDescript_ = !!value;
}
@synthesize descript;
- (void) dealloc {
  self.title = nil;
  self.descript = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.title = @"";
    self.descript = @"";
  }
  return self;
}
static OneMessage_Received* defaultOneMessage_ReceivedInstance = nil;
+ (void) initialize {
  if (self == [OneMessage_Received class]) {
    defaultOneMessage_ReceivedInstance = [[OneMessage_Received alloc] init];
  }
}
+ (OneMessage_Received*) defaultInstance {
  return defaultOneMessage_ReceivedInstance;
}
- (OneMessage_Received*) defaultInstance {
  return defaultOneMessage_ReceivedInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasTitle) {
    [output writeString:1 value:self.title];
  }
  if (self.hasDescript) {
    [output writeString:2 value:self.descript];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasTitle) {
    size += computeStringSize(1, self.title);
  }
  if (self.hasDescript) {
    size += computeStringSize(2, self.descript);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (OneMessage_Received*) parseFromData:(NSData*) data {
  return (OneMessage_Received*)[[[OneMessage_Received builder] mergeFromData:data] build];
}
+ (OneMessage_Received*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (OneMessage_Received*)[[[OneMessage_Received builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (OneMessage_Received*) parseFromInputStream:(NSInputStream*) input {
  return (OneMessage_Received*)[[[OneMessage_Received builder] mergeFromInputStream:input] build];
}
+ (OneMessage_Received*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (OneMessage_Received*)[[[OneMessage_Received builder] mergeDelimitedFromInputStream:input] build];
}
+ (OneMessage_Received*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (OneMessage_Received*)[[[OneMessage_Received builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (OneMessage_Received*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (OneMessage_Received*)[[[OneMessage_Received builder] mergeFromCodedInputStream:input] build];
}
+ (OneMessage_Received*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (OneMessage_Received*)[[[OneMessage_Received builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (OneMessage_Received_Builder*) builder {
  return [[[OneMessage_Received_Builder alloc] init] autorelease];
}
+ (OneMessage_Received_Builder*) builderWithPrototype:(OneMessage_Received*) prototype {
  return [[OneMessage_Received builder] mergeFrom:prototype];
}
- (OneMessage_Received_Builder*) builder {
  return [OneMessage_Received builder];
}
@end

@interface OneMessage_Received_Builder()
@property (retain) OneMessage_Received* result;
@end

@implementation OneMessage_Received_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[OneMessage_Received alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (OneMessage_Received_Builder*) clear {
  self.result = [[[OneMessage_Received alloc] init] autorelease];
  return self;
}
- (OneMessage_Received_Builder*) clone {
  return [OneMessage_Received builderWithPrototype:result];
}
- (OneMessage_Received*) defaultInstance {
  return [OneMessage_Received defaultInstance];
}
- (OneMessage_Received*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (OneMessage_Received*) buildPartial {
  OneMessage_Received* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (OneMessage_Received_Builder*) mergeFrom:(OneMessage_Received*) other {
  if (other == [OneMessage_Received defaultInstance]) {
    return self;
  }
  if (other.hasTitle) {
    [self setTitle:other.title];
  }
  if (other.hasDescript) {
    [self setDescript:other.descript];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (OneMessage_Received_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (OneMessage_Received_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setTitle:[input readString]];
        break;
      }
      case 18: {
        [self setDescript:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasTitle {
  return result.hasTitle;
}
- (NSString*) title {
  return result.title;
}
- (OneMessage_Received_Builder*) setTitle:(NSString*) value {
  result.hasTitle = YES;
  result.title = value;
  return self;
}
- (OneMessage_Received_Builder*) clearTitle {
  result.hasTitle = NO;
  result.title = @"";
  return self;
}
- (BOOL) hasDescript {
  return result.hasDescript;
}
- (NSString*) descript {
  return result.descript;
}
- (OneMessage_Received_Builder*) setDescript:(NSString*) value {
  result.hasDescript = YES;
  result.descript = value;
  return self;
}
- (OneMessage_Received_Builder*) clearDescript {
  result.hasDescript = NO;
  result.descript = @"";
  return self;
}
@end

@interface OneMessage_Builder()
@property (retain) OneMessage* result;
@end

@implementation OneMessage_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[OneMessage alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (OneMessage_Builder*) clear {
  self.result = [[[OneMessage alloc] init] autorelease];
  return self;
}
- (OneMessage_Builder*) clone {
  return [OneMessage builderWithPrototype:result];
}
- (OneMessage*) defaultInstance {
  return [OneMessage defaultInstance];
}
- (OneMessage*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (OneMessage*) buildPartial {
  OneMessage* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (OneMessage_Builder*) mergeFrom:(OneMessage*) other {
  if (other == [OneMessage defaultInstance]) {
    return self;
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasDescript) {
    [self setDescript:other.descript];
  }
  if (other.hasReceipt) {
    [self mergeReceipt:other.receipt];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (OneMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (OneMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setName:[input readString]];
        break;
      }
      case 18: {
        [self setDescript:[input readString]];
        break;
      }
      case 26: {
        OneMessage_Received_Builder* subBuilder = [OneMessage_Received builder];
        if (self.hasReceipt) {
          [subBuilder mergeFrom:self.receipt];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setReceipt:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasName {
  return result.hasName;
}
- (NSString*) name {
  return result.name;
}
- (OneMessage_Builder*) setName:(NSString*) value {
  result.hasName = YES;
  result.name = value;
  return self;
}
- (OneMessage_Builder*) clearName {
  result.hasName = NO;
  result.name = @"";
  return self;
}
- (BOOL) hasDescript {
  return result.hasDescript;
}
- (NSString*) descript {
  return result.descript;
}
- (OneMessage_Builder*) setDescript:(NSString*) value {
  result.hasDescript = YES;
  result.descript = value;
  return self;
}
- (OneMessage_Builder*) clearDescript {
  result.hasDescript = NO;
  result.descript = @"";
  return self;
}
- (BOOL) hasReceipt {
  return result.hasReceipt;
}
- (OneMessage_Received*) receipt {
  return result.receipt;
}
- (OneMessage_Builder*) setReceipt:(OneMessage_Received*) value {
  result.hasReceipt = YES;
  result.receipt = value;
  return self;
}
- (OneMessage_Builder*) setReceiptBuilder:(OneMessage_Received_Builder*) builderForValue {
  return [self setReceipt:[builderForValue build]];
}
- (OneMessage_Builder*) mergeReceipt:(OneMessage_Received*) value {
  if (result.hasReceipt &&
      result.receipt != [OneMessage_Received defaultInstance]) {
    result.receipt =
      [[[OneMessage_Received builderWithPrototype:result.receipt] mergeFrom:value] buildPartial];
  } else {
    result.receipt = value;
  }
  result.hasReceipt = YES;
  return self;
}
- (OneMessage_Builder*) clearReceipt {
  result.hasReceipt = NO;
  result.receipt = [OneMessage_Received defaultInstance];
  return self;
}
@end

