// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class OneMessage;
@class OneMessage_Builder;
@class OneMessage_Received;
@class OneMessage_Received_Builder;

@interface MessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface OneMessage : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasDescript_:1;
  BOOL hasReceipt_:1;
  NSString* name;
  NSString* descript;
  OneMessage_Received* receipt;
}
- (BOOL) hasName;
- (BOOL) hasDescript;
- (BOOL) hasReceipt;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* descript;
@property (readonly, retain) OneMessage_Received* receipt;

+ (OneMessage*) defaultInstance;
- (OneMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OneMessage_Builder*) builder;
+ (OneMessage_Builder*) builder;
+ (OneMessage_Builder*) builderWithPrototype:(OneMessage*) prototype;

+ (OneMessage*) parseFromData:(NSData*) data;
+ (OneMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OneMessage*) parseFromInputStream:(NSInputStream*) input;
+ (OneMessage*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (OneMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OneMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OneMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OneMessage_Received : PBGeneratedMessage {
@private
  BOOL hasTitle_:1;
  BOOL hasDescript_:1;
  NSString* title;
  NSString* descript;
}
- (BOOL) hasTitle;
- (BOOL) hasDescript;
@property (readonly, retain) NSString* title;
@property (readonly, retain) NSString* descript;

+ (OneMessage_Received*) defaultInstance;
- (OneMessage_Received*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (OneMessage_Received_Builder*) builder;
+ (OneMessage_Received_Builder*) builder;
+ (OneMessage_Received_Builder*) builderWithPrototype:(OneMessage_Received*) prototype;

+ (OneMessage_Received*) parseFromData:(NSData*) data;
+ (OneMessage_Received*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OneMessage_Received*) parseFromInputStream:(NSInputStream*) input;
+ (OneMessage_Received*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (OneMessage_Received*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (OneMessage_Received*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (OneMessage_Received*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface OneMessage_Received_Builder : PBGeneratedMessage_Builder {
@private
  OneMessage_Received* result;
}

- (OneMessage_Received*) defaultInstance;

- (OneMessage_Received_Builder*) clear;
- (OneMessage_Received_Builder*) clone;

- (OneMessage_Received*) build;
- (OneMessage_Received*) buildPartial;

- (OneMessage_Received_Builder*) mergeFrom:(OneMessage_Received*) other;
- (OneMessage_Received_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OneMessage_Received_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTitle;
- (NSString*) title;
- (OneMessage_Received_Builder*) setTitle:(NSString*) value;
- (OneMessage_Received_Builder*) clearTitle;

- (BOOL) hasDescript;
- (NSString*) descript;
- (OneMessage_Received_Builder*) setDescript:(NSString*) value;
- (OneMessage_Received_Builder*) clearDescript;
@end

@interface OneMessage_Builder : PBGeneratedMessage_Builder {
@private
  OneMessage* result;
}

- (OneMessage*) defaultInstance;

- (OneMessage_Builder*) clear;
- (OneMessage_Builder*) clone;

- (OneMessage*) build;
- (OneMessage*) buildPartial;

- (OneMessage_Builder*) mergeFrom:(OneMessage*) other;
- (OneMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (OneMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (OneMessage_Builder*) setName:(NSString*) value;
- (OneMessage_Builder*) clearName;

- (BOOL) hasDescript;
- (NSString*) descript;
- (OneMessage_Builder*) setDescript:(NSString*) value;
- (OneMessage_Builder*) clearDescript;

- (BOOL) hasReceipt;
- (OneMessage_Received*) receipt;
- (OneMessage_Builder*) setReceipt:(OneMessage_Received*) value;
- (OneMessage_Builder*) setReceiptBuilder:(OneMessage_Received_Builder*) builderForValue;
- (OneMessage_Builder*) mergeReceipt:(OneMessage_Received*) value;
- (OneMessage_Builder*) clearReceipt;
@end

