// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Repeat;
@class Repeat_Builder;
@class Repeat_Entry;
@class Repeat_Entry_Builder;

@interface RepeatsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Repeat : PBGeneratedMessage {
@private
  BOOL hasTitle_:1;
  NSString* title;
  NSMutableArray* mutableEntryList;
}
- (BOOL) hasTitle;
@property (readonly, retain) NSString* title;
- (NSArray*) entryList;
- (Repeat_Entry*) entryAtIndex:(int32_t) index;

+ (Repeat*) defaultInstance;
- (Repeat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Repeat_Builder*) builder;
+ (Repeat_Builder*) builder;
+ (Repeat_Builder*) builderWithPrototype:(Repeat*) prototype;

+ (Repeat*) parseFromData:(NSData*) data;
+ (Repeat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Repeat*) parseFromInputStream:(NSInputStream*) input;
+ (Repeat*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Repeat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Repeat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Repeat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Repeat_Entry : PBGeneratedMessage {
@private
  BOOL hasTitle_:1;
  NSString* title;
}
- (BOOL) hasTitle;
@property (readonly, retain) NSString* title;

+ (Repeat_Entry*) defaultInstance;
- (Repeat_Entry*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Repeat_Entry_Builder*) builder;
+ (Repeat_Entry_Builder*) builder;
+ (Repeat_Entry_Builder*) builderWithPrototype:(Repeat_Entry*) prototype;

+ (Repeat_Entry*) parseFromData:(NSData*) data;
+ (Repeat_Entry*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Repeat_Entry*) parseFromInputStream:(NSInputStream*) input;
+ (Repeat_Entry*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Repeat_Entry*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Repeat_Entry*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Repeat_Entry*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Repeat_Entry_Builder : PBGeneratedMessage_Builder {
@private
  Repeat_Entry* result;
}

- (Repeat_Entry*) defaultInstance;

- (Repeat_Entry_Builder*) clear;
- (Repeat_Entry_Builder*) clone;

- (Repeat_Entry*) build;
- (Repeat_Entry*) buildPartial;

- (Repeat_Entry_Builder*) mergeFrom:(Repeat_Entry*) other;
- (Repeat_Entry_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Repeat_Entry_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTitle;
- (NSString*) title;
- (Repeat_Entry_Builder*) setTitle:(NSString*) value;
- (Repeat_Entry_Builder*) clearTitle;
@end

@interface Repeat_Builder : PBGeneratedMessage_Builder {
@private
  Repeat* result;
}

- (Repeat*) defaultInstance;

- (Repeat_Builder*) clear;
- (Repeat_Builder*) clone;

- (Repeat*) build;
- (Repeat*) buildPartial;

- (Repeat_Builder*) mergeFrom:(Repeat*) other;
- (Repeat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Repeat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTitle;
- (NSString*) title;
- (Repeat_Builder*) setTitle:(NSString*) value;
- (Repeat_Builder*) clearTitle;

- (NSArray*) entryList;
- (Repeat_Entry*) entryAtIndex:(int32_t) index;
- (Repeat_Builder*) replaceEntryAtIndex:(int32_t) index with:(Repeat_Entry*) value;
- (Repeat_Builder*) addEntry:(Repeat_Entry*) value;
- (Repeat_Builder*) addAllEntry:(NSArray*) values;
- (Repeat_Builder*) clearEntryList;
@end

