// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class Test;
@class Test_Builder;

@interface TestRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface Test : PBGeneratedMessage {
@private
  BOOL hasLongtitude_:1;
  BOOL hasLatitude_:1;
  BOOL hasName_:1;
  BOOL hasDescription_:1;
  Float64 longtitude;
  Float64 latitude;
  NSString* name;
  NSString* description;
}
- (BOOL) hasName;
- (BOOL) hasLongtitude;
- (BOOL) hasLatitude;
- (BOOL) hasDescription;
@property (readonly, retain) NSString* name;
@property (readonly) Float64 longtitude;
@property (readonly) Float64 latitude;
@property (readonly, retain) NSString* description;

+ (Test*) defaultInstance;
- (Test*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (Test_Builder*) builder;
+ (Test_Builder*) builder;
+ (Test_Builder*) builderWithPrototype:(Test*) prototype;

+ (Test*) parseFromData:(NSData*) data;
+ (Test*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Test*) parseFromInputStream:(NSInputStream*) input;
+ (Test*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (Test*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Test*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Test*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface Test_Builder : PBGeneratedMessage_Builder {
@private
  Test* result;
}

- (Test*) defaultInstance;

- (Test_Builder*) clear;
- (Test_Builder*) clone;

- (Test*) build;
- (Test*) buildPartial;

- (Test_Builder*) mergeFrom:(Test*) other;
- (Test_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (Test_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (Test_Builder*) setName:(NSString*) value;
- (Test_Builder*) clearName;

- (BOOL) hasLongtitude;
- (Float64) longtitude;
- (Test_Builder*) setLongtitude:(Float64) value;
- (Test_Builder*) clearLongtitude;

- (BOOL) hasLatitude;
- (Float64) latitude;
- (Test_Builder*) setLatitude:(Float64) value;
- (Test_Builder*) clearLatitude;

- (BOOL) hasDescription;
- (NSString*) description;
- (Test_Builder*) setDescription:(NSString*) value;
- (Test_Builder*) clearDescription;
@end

