// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class GeneralMessage;
@class GeneralMessage_Builder;
typedef enum {
  GeneralMessage_MessageTypeMessageRequest = 1,
  GeneralMessage_MessageTypeMessageReponse = 2,
  GeneralMessage_MessageTypeMessageUses = 3,
} GeneralMessage_MessageType;

BOOL GeneralMessage_MessageTypeIsValidValue(GeneralMessage_MessageType value);


@interface GeneralMessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface GeneralMessage : PBGeneratedMessage {
@private
  BOOL hasMsgPayload_:1;
  BOOL hasMsgType_:1;
  NSData* msgPayload;
  GeneralMessage_MessageType msgType;
}
- (BOOL) hasMsgType;
- (BOOL) hasMsgPayload;
@property (readonly) GeneralMessage_MessageType msgType;
@property (readonly, retain) NSData* msgPayload;

+ (GeneralMessage*) defaultInstance;
- (GeneralMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GeneralMessage_Builder*) builder;
+ (GeneralMessage_Builder*) builder;
+ (GeneralMessage_Builder*) builderWithPrototype:(GeneralMessage*) prototype;

+ (GeneralMessage*) parseFromData:(NSData*) data;
+ (GeneralMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GeneralMessage*) parseFromInputStream:(NSInputStream*) input;
+ (GeneralMessage*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (GeneralMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GeneralMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GeneralMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GeneralMessage_Builder : PBGeneratedMessage_Builder {
@private
  GeneralMessage* result;
}

- (GeneralMessage*) defaultInstance;

- (GeneralMessage_Builder*) clear;
- (GeneralMessage_Builder*) clone;

- (GeneralMessage*) build;
- (GeneralMessage*) buildPartial;

- (GeneralMessage_Builder*) mergeFrom:(GeneralMessage*) other;
- (GeneralMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GeneralMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMsgType;
- (GeneralMessage_MessageType) msgType;
- (GeneralMessage_Builder*) setMsgType:(GeneralMessage_MessageType) value;
- (GeneralMessage_Builder*) clearMsgType;

- (BOOL) hasMsgPayload;
- (NSData*) msgPayload;
- (GeneralMessage_Builder*) setMsgPayload:(NSData*) value;
- (GeneralMessage_Builder*) clearMsgPayload;
@end

