// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "MessageRespose.pb.h"

@implementation MessageResposeRoot
static id<PBExtensionField> PersionSend_persionSend = nil;
static id<PBExtensionField> PersionReceive_persionReceive = nil;
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [MessageResposeRoot class]) {
    PersionSend_persionSend =
      [[PBConcreteExtensionField extensionWithType:PBExtensionTypeMessage
                                     extendedClass:[ResponseMessage class]
                                       fieldNumber:100
                                      defaultValue:[PersionSend defaultInstance]
                               messageOrGroupClass:[PersionSend class]
                                        isRepeated:NO
                                          isPacked:NO
                            isMessageSetWireFormat:NO] retain];
    PersionReceive_persionReceive =
      [[PBConcreteExtensionField extensionWithType:PBExtensionTypeMessage
                                     extendedClass:[ResponseMessage class]
                                       fieldNumber:101
                                      defaultValue:[PersionReceive defaultInstance]
                               messageOrGroupClass:[PersionReceive class]
                                        isRepeated:NO
                                          isPacked:NO
                            isMessageSetWireFormat:NO] retain];
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
  [registry addExtension:PersionSend_persionSend];
  [registry addExtension:PersionReceive_persionReceive];
}
@end

@interface ResponseMessage ()
@property (retain) NSMutableArray* mutableStatusList;
@property (retain) ResponseMessage_ContentMessage* content;
@end

@implementation ResponseMessage

@synthesize mutableStatusList;
- (BOOL) hasContent {
  return !!hasContent_;
}
- (void) setHasContent:(BOOL) value {
  hasContent_ = !!value;
}
@synthesize content;
- (void) dealloc {
  self.mutableStatusList = nil;
  self.content = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.content = [ResponseMessage_ContentMessage defaultInstance];
  }
  return self;
}
static ResponseMessage* defaultResponseMessageInstance = nil;
+ (void) initialize {
  if (self == [ResponseMessage class]) {
    defaultResponseMessageInstance = [[ResponseMessage alloc] init];
  }
}
+ (ResponseMessage*) defaultInstance {
  return defaultResponseMessageInstance;
}
- (ResponseMessage*) defaultInstance {
  return defaultResponseMessageInstance;
}
- (NSArray*) statusList {
  return mutableStatusList;
}
- (ResponseMessage_StatusResponse*) statusAtIndex:(int32_t) index {
  id value = [mutableStatusList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  if (!self.hasContent) {
    return NO;
  }
  for (ResponseMessage_StatusResponse* element in self.statusList) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  if (!self.content.isInitialized) {
    return NO;
  }
  if (!self.extensionsAreInitialized) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (ResponseMessage_StatusResponse* element in self.statusList) {
    [output writeMessage:1 value:element];
  }
  if (self.hasContent) {
    [output writeMessage:2 value:self.content];
  }
  [self writeExtensionsToCodedOutputStream:output
                                      from:100
                                        to:200];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  for (ResponseMessage_StatusResponse* element in self.statusList) {
    size += computeMessageSize(1, element);
  }
  if (self.hasContent) {
    size += computeMessageSize(2, self.content);
  }
  size += [self extensionsSerializedSize];
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (ResponseMessage*) parseFromData:(NSData*) data {
  return (ResponseMessage*)[[[ResponseMessage builder] mergeFromData:data] build];
}
+ (ResponseMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResponseMessage*)[[[ResponseMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ResponseMessage*) parseFromInputStream:(NSInputStream*) input {
  return (ResponseMessage*)[[[ResponseMessage builder] mergeFromInputStream:input] build];
}
+ (ResponseMessage*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (ResponseMessage*)[[[ResponseMessage builder] mergeDelimitedFromInputStream:input] build];
}
+ (ResponseMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResponseMessage*)[[[ResponseMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ResponseMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ResponseMessage*)[[[ResponseMessage builder] mergeFromCodedInputStream:input] build];
}
+ (ResponseMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResponseMessage*)[[[ResponseMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ResponseMessage_Builder*) builder {
  return [[[ResponseMessage_Builder alloc] init] autorelease];
}
+ (ResponseMessage_Builder*) builderWithPrototype:(ResponseMessage*) prototype {
  return [[ResponseMessage builder] mergeFrom:prototype];
}
- (ResponseMessage_Builder*) builder {
  return [ResponseMessage builder];
}
@end

@interface ResponseMessage_StatusResponse ()
@property (retain) NSString* status;
@property int32_t errorCode;
@end

@implementation ResponseMessage_StatusResponse

- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) value {
  hasStatus_ = !!value;
}
@synthesize status;
- (BOOL) hasErrorCode {
  return !!hasErrorCode_;
}
- (void) setHasErrorCode:(BOOL) value {
  hasErrorCode_ = !!value;
}
@synthesize errorCode;
- (void) dealloc {
  self.status = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.status = @"";
    self.errorCode = 0;
  }
  return self;
}
static ResponseMessage_StatusResponse* defaultResponseMessage_StatusResponseInstance = nil;
+ (void) initialize {
  if (self == [ResponseMessage_StatusResponse class]) {
    defaultResponseMessage_StatusResponseInstance = [[ResponseMessage_StatusResponse alloc] init];
  }
}
+ (ResponseMessage_StatusResponse*) defaultInstance {
  return defaultResponseMessage_StatusResponseInstance;
}
- (ResponseMessage_StatusResponse*) defaultInstance {
  return defaultResponseMessage_StatusResponseInstance;
}
- (BOOL) isInitialized {
  if (!self.hasStatus) {
    return NO;
  }
  if (!self.hasErrorCode) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStatus) {
    [output writeString:1 value:self.status];
  }
  if (self.hasErrorCode) {
    [output writeInt32:2 value:self.errorCode];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasStatus) {
    size += computeStringSize(1, self.status);
  }
  if (self.hasErrorCode) {
    size += computeInt32Size(2, self.errorCode);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (ResponseMessage_StatusResponse*) parseFromData:(NSData*) data {
  return (ResponseMessage_StatusResponse*)[[[ResponseMessage_StatusResponse builder] mergeFromData:data] build];
}
+ (ResponseMessage_StatusResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResponseMessage_StatusResponse*)[[[ResponseMessage_StatusResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ResponseMessage_StatusResponse*) parseFromInputStream:(NSInputStream*) input {
  return (ResponseMessage_StatusResponse*)[[[ResponseMessage_StatusResponse builder] mergeFromInputStream:input] build];
}
+ (ResponseMessage_StatusResponse*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (ResponseMessage_StatusResponse*)[[[ResponseMessage_StatusResponse builder] mergeDelimitedFromInputStream:input] build];
}
+ (ResponseMessage_StatusResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResponseMessage_StatusResponse*)[[[ResponseMessage_StatusResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ResponseMessage_StatusResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ResponseMessage_StatusResponse*)[[[ResponseMessage_StatusResponse builder] mergeFromCodedInputStream:input] build];
}
+ (ResponseMessage_StatusResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResponseMessage_StatusResponse*)[[[ResponseMessage_StatusResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ResponseMessage_StatusResponse_Builder*) builder {
  return [[[ResponseMessage_StatusResponse_Builder alloc] init] autorelease];
}
+ (ResponseMessage_StatusResponse_Builder*) builderWithPrototype:(ResponseMessage_StatusResponse*) prototype {
  return [[ResponseMessage_StatusResponse builder] mergeFrom:prototype];
}
- (ResponseMessage_StatusResponse_Builder*) builder {
  return [ResponseMessage_StatusResponse builder];
}
@end

@interface ResponseMessage_StatusResponse_Builder()
@property (retain) ResponseMessage_StatusResponse* result;
@end

@implementation ResponseMessage_StatusResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ResponseMessage_StatusResponse alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ResponseMessage_StatusResponse_Builder*) clear {
  self.result = [[[ResponseMessage_StatusResponse alloc] init] autorelease];
  return self;
}
- (ResponseMessage_StatusResponse_Builder*) clone {
  return [ResponseMessage_StatusResponse builderWithPrototype:result];
}
- (ResponseMessage_StatusResponse*) defaultInstance {
  return [ResponseMessage_StatusResponse defaultInstance];
}
- (ResponseMessage_StatusResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ResponseMessage_StatusResponse*) buildPartial {
  ResponseMessage_StatusResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ResponseMessage_StatusResponse_Builder*) mergeFrom:(ResponseMessage_StatusResponse*) other {
  if (other == [ResponseMessage_StatusResponse defaultInstance]) {
    return self;
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  if (other.hasErrorCode) {
    [self setErrorCode:other.errorCode];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ResponseMessage_StatusResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ResponseMessage_StatusResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setStatus:[input readString]];
        break;
      }
      case 16: {
        [self setErrorCode:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasStatus {
  return result.hasStatus;
}
- (NSString*) status {
  return result.status;
}
- (ResponseMessage_StatusResponse_Builder*) setStatus:(NSString*) value {
  result.hasStatus = YES;
  result.status = value;
  return self;
}
- (ResponseMessage_StatusResponse_Builder*) clearStatus {
  result.hasStatus = NO;
  result.status = @"";
  return self;
}
- (BOOL) hasErrorCode {
  return result.hasErrorCode;
}
- (int32_t) errorCode {
  return result.errorCode;
}
- (ResponseMessage_StatusResponse_Builder*) setErrorCode:(int32_t) value {
  result.hasErrorCode = YES;
  result.errorCode = value;
  return self;
}
- (ResponseMessage_StatusResponse_Builder*) clearErrorCode {
  result.hasErrorCode = NO;
  result.errorCode = 0;
  return self;
}
@end

@interface ResponseMessage_ContentMessage ()
@property int64_t messageId;
@property (retain) NSString* timeCreate;
@property (retain) NSString* content;
@end

@implementation ResponseMessage_ContentMessage

- (BOOL) hasMessageId {
  return !!hasMessageId_;
}
- (void) setHasMessageId:(BOOL) value {
  hasMessageId_ = !!value;
}
@synthesize messageId;
- (BOOL) hasTimeCreate {
  return !!hasTimeCreate_;
}
- (void) setHasTimeCreate:(BOOL) value {
  hasTimeCreate_ = !!value;
}
@synthesize timeCreate;
- (BOOL) hasContent {
  return !!hasContent_;
}
- (void) setHasContent:(BOOL) value {
  hasContent_ = !!value;
}
@synthesize content;
- (void) dealloc {
  self.timeCreate = nil;
  self.content = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.messageId = 0L;
    self.timeCreate = @"";
    self.content = @"";
  }
  return self;
}
static ResponseMessage_ContentMessage* defaultResponseMessage_ContentMessageInstance = nil;
+ (void) initialize {
  if (self == [ResponseMessage_ContentMessage class]) {
    defaultResponseMessage_ContentMessageInstance = [[ResponseMessage_ContentMessage alloc] init];
  }
}
+ (ResponseMessage_ContentMessage*) defaultInstance {
  return defaultResponseMessage_ContentMessageInstance;
}
- (ResponseMessage_ContentMessage*) defaultInstance {
  return defaultResponseMessage_ContentMessageInstance;
}
- (BOOL) isInitialized {
  if (!self.hasMessageId) {
    return NO;
  }
  if (!self.hasTimeCreate) {
    return NO;
  }
  if (!self.hasContent) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasMessageId) {
    [output writeInt64:1 value:self.messageId];
  }
  if (self.hasTimeCreate) {
    [output writeString:2 value:self.timeCreate];
  }
  if (self.hasContent) {
    [output writeString:3 value:self.content];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasMessageId) {
    size += computeInt64Size(1, self.messageId);
  }
  if (self.hasTimeCreate) {
    size += computeStringSize(2, self.timeCreate);
  }
  if (self.hasContent) {
    size += computeStringSize(3, self.content);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (ResponseMessage_ContentMessage*) parseFromData:(NSData*) data {
  return (ResponseMessage_ContentMessage*)[[[ResponseMessage_ContentMessage builder] mergeFromData:data] build];
}
+ (ResponseMessage_ContentMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResponseMessage_ContentMessage*)[[[ResponseMessage_ContentMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ResponseMessage_ContentMessage*) parseFromInputStream:(NSInputStream*) input {
  return (ResponseMessage_ContentMessage*)[[[ResponseMessage_ContentMessage builder] mergeFromInputStream:input] build];
}
+ (ResponseMessage_ContentMessage*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (ResponseMessage_ContentMessage*)[[[ResponseMessage_ContentMessage builder] mergeDelimitedFromInputStream:input] build];
}
+ (ResponseMessage_ContentMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResponseMessage_ContentMessage*)[[[ResponseMessage_ContentMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ResponseMessage_ContentMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ResponseMessage_ContentMessage*)[[[ResponseMessage_ContentMessage builder] mergeFromCodedInputStream:input] build];
}
+ (ResponseMessage_ContentMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResponseMessage_ContentMessage*)[[[ResponseMessage_ContentMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ResponseMessage_ContentMessage_Builder*) builder {
  return [[[ResponseMessage_ContentMessage_Builder alloc] init] autorelease];
}
+ (ResponseMessage_ContentMessage_Builder*) builderWithPrototype:(ResponseMessage_ContentMessage*) prototype {
  return [[ResponseMessage_ContentMessage builder] mergeFrom:prototype];
}
- (ResponseMessage_ContentMessage_Builder*) builder {
  return [ResponseMessage_ContentMessage builder];
}
@end

@interface ResponseMessage_ContentMessage_Builder()
@property (retain) ResponseMessage_ContentMessage* result;
@end

@implementation ResponseMessage_ContentMessage_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ResponseMessage_ContentMessage alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ResponseMessage_ContentMessage_Builder*) clear {
  self.result = [[[ResponseMessage_ContentMessage alloc] init] autorelease];
  return self;
}
- (ResponseMessage_ContentMessage_Builder*) clone {
  return [ResponseMessage_ContentMessage builderWithPrototype:result];
}
- (ResponseMessage_ContentMessage*) defaultInstance {
  return [ResponseMessage_ContentMessage defaultInstance];
}
- (ResponseMessage_ContentMessage*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ResponseMessage_ContentMessage*) buildPartial {
  ResponseMessage_ContentMessage* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ResponseMessage_ContentMessage_Builder*) mergeFrom:(ResponseMessage_ContentMessage*) other {
  if (other == [ResponseMessage_ContentMessage defaultInstance]) {
    return self;
  }
  if (other.hasMessageId) {
    [self setMessageId:other.messageId];
  }
  if (other.hasTimeCreate) {
    [self setTimeCreate:other.timeCreate];
  }
  if (other.hasContent) {
    [self setContent:other.content];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ResponseMessage_ContentMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ResponseMessage_ContentMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setMessageId:[input readInt64]];
        break;
      }
      case 18: {
        [self setTimeCreate:[input readString]];
        break;
      }
      case 26: {
        [self setContent:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasMessageId {
  return result.hasMessageId;
}
- (int64_t) messageId {
  return result.messageId;
}
- (ResponseMessage_ContentMessage_Builder*) setMessageId:(int64_t) value {
  result.hasMessageId = YES;
  result.messageId = value;
  return self;
}
- (ResponseMessage_ContentMessage_Builder*) clearMessageId {
  result.hasMessageId = NO;
  result.messageId = 0L;
  return self;
}
- (BOOL) hasTimeCreate {
  return result.hasTimeCreate;
}
- (NSString*) timeCreate {
  return result.timeCreate;
}
- (ResponseMessage_ContentMessage_Builder*) setTimeCreate:(NSString*) value {
  result.hasTimeCreate = YES;
  result.timeCreate = value;
  return self;
}
- (ResponseMessage_ContentMessage_Builder*) clearTimeCreate {
  result.hasTimeCreate = NO;
  result.timeCreate = @"";
  return self;
}
- (BOOL) hasContent {
  return result.hasContent;
}
- (NSString*) content {
  return result.content;
}
- (ResponseMessage_ContentMessage_Builder*) setContent:(NSString*) value {
  result.hasContent = YES;
  result.content = value;
  return self;
}
- (ResponseMessage_ContentMessage_Builder*) clearContent {
  result.hasContent = NO;
  result.content = @"";
  return self;
}
@end

@interface ResponseMessage_Builder()
@property (retain) ResponseMessage* result;
@end

@implementation ResponseMessage_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ResponseMessage alloc] init] autorelease];
  }
  return self;
}
- (PBExtendableMessage*) internalGetResult {
  return result;
}
- (ResponseMessage_Builder*) clear {
  self.result = [[[ResponseMessage alloc] init] autorelease];
  return self;
}
- (ResponseMessage_Builder*) clone {
  return [ResponseMessage builderWithPrototype:result];
}
- (ResponseMessage*) defaultInstance {
  return [ResponseMessage defaultInstance];
}
- (ResponseMessage*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ResponseMessage*) buildPartial {
  ResponseMessage* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ResponseMessage_Builder*) mergeFrom:(ResponseMessage*) other {
  if (other == [ResponseMessage defaultInstance]) {
    return self;
  }
  if (other.mutableStatusList.count > 0) {
    if (result.mutableStatusList == nil) {
      result.mutableStatusList = [NSMutableArray array];
    }
    [result.mutableStatusList addObjectsFromArray:other.mutableStatusList];
  }
  if (other.hasContent) {
    [self mergeContent:other.content];
  }
  [self mergeExtensionFields:other];
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ResponseMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ResponseMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        ResponseMessage_StatusResponse_Builder* subBuilder = [ResponseMessage_StatusResponse builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addStatus:[subBuilder buildPartial]];
        break;
      }
      case 18: {
        ResponseMessage_ContentMessage_Builder* subBuilder = [ResponseMessage_ContentMessage builder];
        if (self.hasContent) {
          [subBuilder mergeFrom:self.content];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setContent:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSArray*) statusList {
  if (result.mutableStatusList == nil) { return [NSArray array]; }
  return result.mutableStatusList;
}
- (ResponseMessage_StatusResponse*) statusAtIndex:(int32_t) index {
  return [result statusAtIndex:index];
}
- (ResponseMessage_Builder*) replaceStatusAtIndex:(int32_t) index with:(ResponseMessage_StatusResponse*) value {
  [result.mutableStatusList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (ResponseMessage_Builder*) addAllStatus:(NSArray*) values {
  if (result.mutableStatusList == nil) {
    result.mutableStatusList = [NSMutableArray array];
  }
  [result.mutableStatusList addObjectsFromArray:values];
  return self;
}
- (ResponseMessage_Builder*) clearStatusList {
  result.mutableStatusList = nil;
  return self;
}
- (ResponseMessage_Builder*) addStatus:(ResponseMessage_StatusResponse*) value {
  if (result.mutableStatusList == nil) {
    result.mutableStatusList = [NSMutableArray array];
  }
  [result.mutableStatusList addObject:value];
  return self;
}
- (BOOL) hasContent {
  return result.hasContent;
}
- (ResponseMessage_ContentMessage*) content {
  return result.content;
}
- (ResponseMessage_Builder*) setContent:(ResponseMessage_ContentMessage*) value {
  result.hasContent = YES;
  result.content = value;
  return self;
}
- (ResponseMessage_Builder*) setContentBuilder:(ResponseMessage_ContentMessage_Builder*) builderForValue {
  return [self setContent:[builderForValue build]];
}
- (ResponseMessage_Builder*) mergeContent:(ResponseMessage_ContentMessage*) value {
  if (result.hasContent &&
      result.content != [ResponseMessage_ContentMessage defaultInstance]) {
    result.content =
      [[[ResponseMessage_ContentMessage builderWithPrototype:result.content] mergeFrom:value] buildPartial];
  } else {
    result.content = value;
  }
  result.hasContent = YES;
  return self;
}
- (ResponseMessage_Builder*) clearContent {
  result.hasContent = NO;
  result.content = [ResponseMessage_ContentMessage defaultInstance];
  return self;
}
@end

@interface PersionSend ()
@property int32_t userId;
@property (retain) NSString* userName;
@property (retain) NSData* userAvatar;
@end

@implementation PersionSend

- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) value {
  hasUserId_ = !!value;
}
@synthesize userId;
- (BOOL) hasUserName {
  return !!hasUserName_;
}
- (void) setHasUserName:(BOOL) value {
  hasUserName_ = !!value;
}
@synthesize userName;
- (BOOL) hasUserAvatar {
  return !!hasUserAvatar_;
}
- (void) setHasUserAvatar:(BOOL) value {
  hasUserAvatar_ = !!value;
}
@synthesize userAvatar;
- (void) dealloc {
  self.userName = nil;
  self.userAvatar = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.userId = 0;
    self.userName = @"";
    self.userAvatar = [NSData data];
  }
  return self;
}
+ (id<PBExtensionField>) persionSend {
  return PersionSend_persionSend;
}
static PersionSend* defaultPersionSendInstance = nil;
+ (void) initialize {
  if (self == [PersionSend class]) {
    defaultPersionSendInstance = [[PersionSend alloc] init];
  }
}
+ (PersionSend*) defaultInstance {
  return defaultPersionSendInstance;
}
- (PersionSend*) defaultInstance {
  return defaultPersionSendInstance;
}
- (BOOL) isInitialized {
  if (!self.hasUserId) {
    return NO;
  }
  if (!self.hasUserName) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUserId) {
    [output writeInt32:1 value:self.userId];
  }
  if (self.hasUserName) {
    [output writeString:2 value:self.userName];
  }
  if (self.hasUserAvatar) {
    [output writeData:3 value:self.userAvatar];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasUserId) {
    size += computeInt32Size(1, self.userId);
  }
  if (self.hasUserName) {
    size += computeStringSize(2, self.userName);
  }
  if (self.hasUserAvatar) {
    size += computeDataSize(3, self.userAvatar);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (PersionSend*) parseFromData:(NSData*) data {
  return (PersionSend*)[[[PersionSend builder] mergeFromData:data] build];
}
+ (PersionSend*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PersionSend*)[[[PersionSend builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PersionSend*) parseFromInputStream:(NSInputStream*) input {
  return (PersionSend*)[[[PersionSend builder] mergeFromInputStream:input] build];
}
+ (PersionSend*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (PersionSend*)[[[PersionSend builder] mergeDelimitedFromInputStream:input] build];
}
+ (PersionSend*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PersionSend*)[[[PersionSend builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PersionSend*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PersionSend*)[[[PersionSend builder] mergeFromCodedInputStream:input] build];
}
+ (PersionSend*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PersionSend*)[[[PersionSend builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PersionSend_Builder*) builder {
  return [[[PersionSend_Builder alloc] init] autorelease];
}
+ (PersionSend_Builder*) builderWithPrototype:(PersionSend*) prototype {
  return [[PersionSend builder] mergeFrom:prototype];
}
- (PersionSend_Builder*) builder {
  return [PersionSend builder];
}
@end

@interface PersionSend_Builder()
@property (retain) PersionSend* result;
@end

@implementation PersionSend_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PersionSend alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PersionSend_Builder*) clear {
  self.result = [[[PersionSend alloc] init] autorelease];
  return self;
}
- (PersionSend_Builder*) clone {
  return [PersionSend builderWithPrototype:result];
}
- (PersionSend*) defaultInstance {
  return [PersionSend defaultInstance];
}
- (PersionSend*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PersionSend*) buildPartial {
  PersionSend* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PersionSend_Builder*) mergeFrom:(PersionSend*) other {
  if (other == [PersionSend defaultInstance]) {
    return self;
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  if (other.hasUserName) {
    [self setUserName:other.userName];
  }
  if (other.hasUserAvatar) {
    [self setUserAvatar:other.userAvatar];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PersionSend_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PersionSend_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setUserId:[input readInt32]];
        break;
      }
      case 18: {
        [self setUserName:[input readString]];
        break;
      }
      case 26: {
        [self setUserAvatar:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasUserId {
  return result.hasUserId;
}
- (int32_t) userId {
  return result.userId;
}
- (PersionSend_Builder*) setUserId:(int32_t) value {
  result.hasUserId = YES;
  result.userId = value;
  return self;
}
- (PersionSend_Builder*) clearUserId {
  result.hasUserId = NO;
  result.userId = 0;
  return self;
}
- (BOOL) hasUserName {
  return result.hasUserName;
}
- (NSString*) userName {
  return result.userName;
}
- (PersionSend_Builder*) setUserName:(NSString*) value {
  result.hasUserName = YES;
  result.userName = value;
  return self;
}
- (PersionSend_Builder*) clearUserName {
  result.hasUserName = NO;
  result.userName = @"";
  return self;
}
- (BOOL) hasUserAvatar {
  return result.hasUserAvatar;
}
- (NSData*) userAvatar {
  return result.userAvatar;
}
- (PersionSend_Builder*) setUserAvatar:(NSData*) value {
  result.hasUserAvatar = YES;
  result.userAvatar = value;
  return self;
}
- (PersionSend_Builder*) clearUserAvatar {
  result.hasUserAvatar = NO;
  result.userAvatar = [NSData data];
  return self;
}
@end

@interface PersionReceive ()
@property int32_t userId;
@property (retain) NSString* userName;
@property (retain) NSData* userAvatar;
@end

@implementation PersionReceive

- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) value {
  hasUserId_ = !!value;
}
@synthesize userId;
- (BOOL) hasUserName {
  return !!hasUserName_;
}
- (void) setHasUserName:(BOOL) value {
  hasUserName_ = !!value;
}
@synthesize userName;
- (BOOL) hasUserAvatar {
  return !!hasUserAvatar_;
}
- (void) setHasUserAvatar:(BOOL) value {
  hasUserAvatar_ = !!value;
}
@synthesize userAvatar;
- (void) dealloc {
  self.userName = nil;
  self.userAvatar = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.userId = 0;
    self.userName = @"";
    self.userAvatar = [NSData data];
  }
  return self;
}
+ (id<PBExtensionField>) persionReceive {
  return PersionReceive_persionReceive;
}
static PersionReceive* defaultPersionReceiveInstance = nil;
+ (void) initialize {
  if (self == [PersionReceive class]) {
    defaultPersionReceiveInstance = [[PersionReceive alloc] init];
  }
}
+ (PersionReceive*) defaultInstance {
  return defaultPersionReceiveInstance;
}
- (PersionReceive*) defaultInstance {
  return defaultPersionReceiveInstance;
}
- (BOOL) isInitialized {
  if (!self.hasUserId) {
    return NO;
  }
  if (!self.hasUserName) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUserId) {
    [output writeInt32:1 value:self.userId];
  }
  if (self.hasUserName) {
    [output writeString:2 value:self.userName];
  }
  if (self.hasUserAvatar) {
    [output writeData:3 value:self.userAvatar];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasUserId) {
    size += computeInt32Size(1, self.userId);
  }
  if (self.hasUserName) {
    size += computeStringSize(2, self.userName);
  }
  if (self.hasUserAvatar) {
    size += computeDataSize(3, self.userAvatar);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (PersionReceive*) parseFromData:(NSData*) data {
  return (PersionReceive*)[[[PersionReceive builder] mergeFromData:data] build];
}
+ (PersionReceive*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PersionReceive*)[[[PersionReceive builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (PersionReceive*) parseFromInputStream:(NSInputStream*) input {
  return (PersionReceive*)[[[PersionReceive builder] mergeFromInputStream:input] build];
}
+ (PersionReceive*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (PersionReceive*)[[[PersionReceive builder] mergeDelimitedFromInputStream:input] build];
}
+ (PersionReceive*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PersionReceive*)[[[PersionReceive builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PersionReceive*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (PersionReceive*)[[[PersionReceive builder] mergeFromCodedInputStream:input] build];
}
+ (PersionReceive*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (PersionReceive*)[[[PersionReceive builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (PersionReceive_Builder*) builder {
  return [[[PersionReceive_Builder alloc] init] autorelease];
}
+ (PersionReceive_Builder*) builderWithPrototype:(PersionReceive*) prototype {
  return [[PersionReceive builder] mergeFrom:prototype];
}
- (PersionReceive_Builder*) builder {
  return [PersionReceive builder];
}
@end

@interface PersionReceive_Builder()
@property (retain) PersionReceive* result;
@end

@implementation PersionReceive_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[PersionReceive alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (PersionReceive_Builder*) clear {
  self.result = [[[PersionReceive alloc] init] autorelease];
  return self;
}
- (PersionReceive_Builder*) clone {
  return [PersionReceive builderWithPrototype:result];
}
- (PersionReceive*) defaultInstance {
  return [PersionReceive defaultInstance];
}
- (PersionReceive*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (PersionReceive*) buildPartial {
  PersionReceive* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (PersionReceive_Builder*) mergeFrom:(PersionReceive*) other {
  if (other == [PersionReceive defaultInstance]) {
    return self;
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  if (other.hasUserName) {
    [self setUserName:other.userName];
  }
  if (other.hasUserAvatar) {
    [self setUserAvatar:other.userAvatar];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (PersionReceive_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (PersionReceive_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setUserId:[input readInt32]];
        break;
      }
      case 18: {
        [self setUserName:[input readString]];
        break;
      }
      case 26: {
        [self setUserAvatar:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasUserId {
  return result.hasUserId;
}
- (int32_t) userId {
  return result.userId;
}
- (PersionReceive_Builder*) setUserId:(int32_t) value {
  result.hasUserId = YES;
  result.userId = value;
  return self;
}
- (PersionReceive_Builder*) clearUserId {
  result.hasUserId = NO;
  result.userId = 0;
  return self;
}
- (BOOL) hasUserName {
  return result.hasUserName;
}
- (NSString*) userName {
  return result.userName;
}
- (PersionReceive_Builder*) setUserName:(NSString*) value {
  result.hasUserName = YES;
  result.userName = value;
  return self;
}
- (PersionReceive_Builder*) clearUserName {
  result.hasUserName = NO;
  result.userName = @"";
  return self;
}
- (BOOL) hasUserAvatar {
  return result.hasUserAvatar;
}
- (NSData*) userAvatar {
  return result.userAvatar;
}
- (PersionReceive_Builder*) setUserAvatar:(NSData*) value {
  result.hasUserAvatar = YES;
  result.userAvatar = value;
  return self;
}
- (PersionReceive_Builder*) clearUserAvatar {
  result.hasUserAvatar = NO;
  result.userAvatar = [NSData data];
  return self;
}
@end

