// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "MessageRequest.pb.h"

@implementation MessageRequestRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [MessageRequestRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface RequestMessage ()
@property (retain) NSString* content;
@property (retain) RequestMessage_PersionReceipt* perReceipt;
@property (retain) RequestMessage_PersionSend* perSend;
@end

@implementation RequestMessage

- (BOOL) hasContent {
  return !!hasContent_;
}
- (void) setHasContent:(BOOL) value {
  hasContent_ = !!value;
}
@synthesize content;
- (BOOL) hasPerReceipt {
  return !!hasPerReceipt_;
}
- (void) setHasPerReceipt:(BOOL) value {
  hasPerReceipt_ = !!value;
}
@synthesize perReceipt;
- (BOOL) hasPerSend {
  return !!hasPerSend_;
}
- (void) setHasPerSend:(BOOL) value {
  hasPerSend_ = !!value;
}
@synthesize perSend;
- (void) dealloc {
  self.content = nil;
  self.perReceipt = nil;
  self.perSend = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.content = @"";
    self.perReceipt = [RequestMessage_PersionReceipt defaultInstance];
    self.perSend = [RequestMessage_PersionSend defaultInstance];
  }
  return self;
}
static RequestMessage* defaultRequestMessageInstance = nil;
+ (void) initialize {
  if (self == [RequestMessage class]) {
    defaultRequestMessageInstance = [[RequestMessage alloc] init];
  }
}
+ (RequestMessage*) defaultInstance {
  return defaultRequestMessageInstance;
}
- (RequestMessage*) defaultInstance {
  return defaultRequestMessageInstance;
}
- (BOOL) isInitialized {
  if (!self.hasContent) {
    return NO;
  }
  if (!self.hasPerReceipt) {
    return NO;
  }
  if (!self.hasPerSend) {
    return NO;
  }
  if (!self.perReceipt.isInitialized) {
    return NO;
  }
  if (!self.perSend.isInitialized) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasContent) {
    [output writeString:1 value:self.content];
  }
  if (self.hasPerReceipt) {
    [output writeMessage:2 value:self.perReceipt];
  }
  if (self.hasPerSend) {
    [output writeMessage:3 value:self.perSend];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasContent) {
    size += computeStringSize(1, self.content);
  }
  if (self.hasPerReceipt) {
    size += computeMessageSize(2, self.perReceipt);
  }
  if (self.hasPerSend) {
    size += computeMessageSize(3, self.perSend);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (RequestMessage*) parseFromData:(NSData*) data {
  return (RequestMessage*)[[[RequestMessage builder] mergeFromData:data] build];
}
+ (RequestMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestMessage*)[[[RequestMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RequestMessage*) parseFromInputStream:(NSInputStream*) input {
  return (RequestMessage*)[[[RequestMessage builder] mergeFromInputStream:input] build];
}
+ (RequestMessage*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (RequestMessage*)[[[RequestMessage builder] mergeDelimitedFromInputStream:input] build];
}
+ (RequestMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestMessage*)[[[RequestMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RequestMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RequestMessage*)[[[RequestMessage builder] mergeFromCodedInputStream:input] build];
}
+ (RequestMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestMessage*)[[[RequestMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RequestMessage_Builder*) builder {
  return [[[RequestMessage_Builder alloc] init] autorelease];
}
+ (RequestMessage_Builder*) builderWithPrototype:(RequestMessage*) prototype {
  return [[RequestMessage builder] mergeFrom:prototype];
}
- (RequestMessage_Builder*) builder {
  return [RequestMessage builder];
}
@end

@interface RequestMessage_PersionReceipt ()
@property int32_t userId;
@property (retain) NSString* userName;
@property (retain) NSData* userAvatar;
@end

@implementation RequestMessage_PersionReceipt

- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) value {
  hasUserId_ = !!value;
}
@synthesize userId;
- (BOOL) hasUserName {
  return !!hasUserName_;
}
- (void) setHasUserName:(BOOL) value {
  hasUserName_ = !!value;
}
@synthesize userName;
- (BOOL) hasUserAvatar {
  return !!hasUserAvatar_;
}
- (void) setHasUserAvatar:(BOOL) value {
  hasUserAvatar_ = !!value;
}
@synthesize userAvatar;
- (void) dealloc {
  self.userName = nil;
  self.userAvatar = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.userId = 0;
    self.userName = @"";
    self.userAvatar = [NSData data];
  }
  return self;
}
static RequestMessage_PersionReceipt* defaultRequestMessage_PersionReceiptInstance = nil;
+ (void) initialize {
  if (self == [RequestMessage_PersionReceipt class]) {
    defaultRequestMessage_PersionReceiptInstance = [[RequestMessage_PersionReceipt alloc] init];
  }
}
+ (RequestMessage_PersionReceipt*) defaultInstance {
  return defaultRequestMessage_PersionReceiptInstance;
}
- (RequestMessage_PersionReceipt*) defaultInstance {
  return defaultRequestMessage_PersionReceiptInstance;
}
- (BOOL) isInitialized {
  if (!self.hasUserId) {
    return NO;
  }
  if (!self.hasUserName) {
    return NO;
  }
  if (!self.hasUserAvatar) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUserId) {
    [output writeInt32:1 value:self.userId];
  }
  if (self.hasUserName) {
    [output writeString:2 value:self.userName];
  }
  if (self.hasUserAvatar) {
    [output writeData:3 value:self.userAvatar];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasUserId) {
    size += computeInt32Size(1, self.userId);
  }
  if (self.hasUserName) {
    size += computeStringSize(2, self.userName);
  }
  if (self.hasUserAvatar) {
    size += computeDataSize(3, self.userAvatar);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (RequestMessage_PersionReceipt*) parseFromData:(NSData*) data {
  return (RequestMessage_PersionReceipt*)[[[RequestMessage_PersionReceipt builder] mergeFromData:data] build];
}
+ (RequestMessage_PersionReceipt*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestMessage_PersionReceipt*)[[[RequestMessage_PersionReceipt builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RequestMessage_PersionReceipt*) parseFromInputStream:(NSInputStream*) input {
  return (RequestMessage_PersionReceipt*)[[[RequestMessage_PersionReceipt builder] mergeFromInputStream:input] build];
}
+ (RequestMessage_PersionReceipt*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (RequestMessage_PersionReceipt*)[[[RequestMessage_PersionReceipt builder] mergeDelimitedFromInputStream:input] build];
}
+ (RequestMessage_PersionReceipt*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestMessage_PersionReceipt*)[[[RequestMessage_PersionReceipt builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RequestMessage_PersionReceipt*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RequestMessage_PersionReceipt*)[[[RequestMessage_PersionReceipt builder] mergeFromCodedInputStream:input] build];
}
+ (RequestMessage_PersionReceipt*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestMessage_PersionReceipt*)[[[RequestMessage_PersionReceipt builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RequestMessage_PersionReceipt_Builder*) builder {
  return [[[RequestMessage_PersionReceipt_Builder alloc] init] autorelease];
}
+ (RequestMessage_PersionReceipt_Builder*) builderWithPrototype:(RequestMessage_PersionReceipt*) prototype {
  return [[RequestMessage_PersionReceipt builder] mergeFrom:prototype];
}
- (RequestMessage_PersionReceipt_Builder*) builder {
  return [RequestMessage_PersionReceipt builder];
}
@end

@interface RequestMessage_PersionReceipt_Builder()
@property (retain) RequestMessage_PersionReceipt* result;
@end

@implementation RequestMessage_PersionReceipt_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[RequestMessage_PersionReceipt alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (RequestMessage_PersionReceipt_Builder*) clear {
  self.result = [[[RequestMessage_PersionReceipt alloc] init] autorelease];
  return self;
}
- (RequestMessage_PersionReceipt_Builder*) clone {
  return [RequestMessage_PersionReceipt builderWithPrototype:result];
}
- (RequestMessage_PersionReceipt*) defaultInstance {
  return [RequestMessage_PersionReceipt defaultInstance];
}
- (RequestMessage_PersionReceipt*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RequestMessage_PersionReceipt*) buildPartial {
  RequestMessage_PersionReceipt* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (RequestMessage_PersionReceipt_Builder*) mergeFrom:(RequestMessage_PersionReceipt*) other {
  if (other == [RequestMessage_PersionReceipt defaultInstance]) {
    return self;
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  if (other.hasUserName) {
    [self setUserName:other.userName];
  }
  if (other.hasUserAvatar) {
    [self setUserAvatar:other.userAvatar];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RequestMessage_PersionReceipt_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RequestMessage_PersionReceipt_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setUserId:[input readInt32]];
        break;
      }
      case 18: {
        [self setUserName:[input readString]];
        break;
      }
      case 26: {
        [self setUserAvatar:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasUserId {
  return result.hasUserId;
}
- (int32_t) userId {
  return result.userId;
}
- (RequestMessage_PersionReceipt_Builder*) setUserId:(int32_t) value {
  result.hasUserId = YES;
  result.userId = value;
  return self;
}
- (RequestMessage_PersionReceipt_Builder*) clearUserId {
  result.hasUserId = NO;
  result.userId = 0;
  return self;
}
- (BOOL) hasUserName {
  return result.hasUserName;
}
- (NSString*) userName {
  return result.userName;
}
- (RequestMessage_PersionReceipt_Builder*) setUserName:(NSString*) value {
  result.hasUserName = YES;
  result.userName = value;
  return self;
}
- (RequestMessage_PersionReceipt_Builder*) clearUserName {
  result.hasUserName = NO;
  result.userName = @"";
  return self;
}
- (BOOL) hasUserAvatar {
  return result.hasUserAvatar;
}
- (NSData*) userAvatar {
  return result.userAvatar;
}
- (RequestMessage_PersionReceipt_Builder*) setUserAvatar:(NSData*) value {
  result.hasUserAvatar = YES;
  result.userAvatar = value;
  return self;
}
- (RequestMessage_PersionReceipt_Builder*) clearUserAvatar {
  result.hasUserAvatar = NO;
  result.userAvatar = [NSData data];
  return self;
}
@end

@interface RequestMessage_PersionSend ()
@property int32_t userId;
@property (retain) NSString* userName;
@property (retain) NSData* userAvatar;
@end

@implementation RequestMessage_PersionSend

- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) value {
  hasUserId_ = !!value;
}
@synthesize userId;
- (BOOL) hasUserName {
  return !!hasUserName_;
}
- (void) setHasUserName:(BOOL) value {
  hasUserName_ = !!value;
}
@synthesize userName;
- (BOOL) hasUserAvatar {
  return !!hasUserAvatar_;
}
- (void) setHasUserAvatar:(BOOL) value {
  hasUserAvatar_ = !!value;
}
@synthesize userAvatar;
- (void) dealloc {
  self.userName = nil;
  self.userAvatar = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.userId = 0;
    self.userName = @"";
    self.userAvatar = [NSData data];
  }
  return self;
}
static RequestMessage_PersionSend* defaultRequestMessage_PersionSendInstance = nil;
+ (void) initialize {
  if (self == [RequestMessage_PersionSend class]) {
    defaultRequestMessage_PersionSendInstance = [[RequestMessage_PersionSend alloc] init];
  }
}
+ (RequestMessage_PersionSend*) defaultInstance {
  return defaultRequestMessage_PersionSendInstance;
}
- (RequestMessage_PersionSend*) defaultInstance {
  return defaultRequestMessage_PersionSendInstance;
}
- (BOOL) isInitialized {
  if (!self.hasUserId) {
    return NO;
  }
  if (!self.hasUserName) {
    return NO;
  }
  if (!self.hasUserAvatar) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUserId) {
    [output writeInt32:1 value:self.userId];
  }
  if (self.hasUserName) {
    [output writeString:2 value:self.userName];
  }
  if (self.hasUserAvatar) {
    [output writeData:3 value:self.userAvatar];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasUserId) {
    size += computeInt32Size(1, self.userId);
  }
  if (self.hasUserName) {
    size += computeStringSize(2, self.userName);
  }
  if (self.hasUserAvatar) {
    size += computeDataSize(3, self.userAvatar);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (RequestMessage_PersionSend*) parseFromData:(NSData*) data {
  return (RequestMessage_PersionSend*)[[[RequestMessage_PersionSend builder] mergeFromData:data] build];
}
+ (RequestMessage_PersionSend*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestMessage_PersionSend*)[[[RequestMessage_PersionSend builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RequestMessage_PersionSend*) parseFromInputStream:(NSInputStream*) input {
  return (RequestMessage_PersionSend*)[[[RequestMessage_PersionSend builder] mergeFromInputStream:input] build];
}
+ (RequestMessage_PersionSend*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (RequestMessage_PersionSend*)[[[RequestMessage_PersionSend builder] mergeDelimitedFromInputStream:input] build];
}
+ (RequestMessage_PersionSend*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestMessage_PersionSend*)[[[RequestMessage_PersionSend builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RequestMessage_PersionSend*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RequestMessage_PersionSend*)[[[RequestMessage_PersionSend builder] mergeFromCodedInputStream:input] build];
}
+ (RequestMessage_PersionSend*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestMessage_PersionSend*)[[[RequestMessage_PersionSend builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RequestMessage_PersionSend_Builder*) builder {
  return [[[RequestMessage_PersionSend_Builder alloc] init] autorelease];
}
+ (RequestMessage_PersionSend_Builder*) builderWithPrototype:(RequestMessage_PersionSend*) prototype {
  return [[RequestMessage_PersionSend builder] mergeFrom:prototype];
}
- (RequestMessage_PersionSend_Builder*) builder {
  return [RequestMessage_PersionSend builder];
}
@end

@interface RequestMessage_PersionSend_Builder()
@property (retain) RequestMessage_PersionSend* result;
@end

@implementation RequestMessage_PersionSend_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[RequestMessage_PersionSend alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (RequestMessage_PersionSend_Builder*) clear {
  self.result = [[[RequestMessage_PersionSend alloc] init] autorelease];
  return self;
}
- (RequestMessage_PersionSend_Builder*) clone {
  return [RequestMessage_PersionSend builderWithPrototype:result];
}
- (RequestMessage_PersionSend*) defaultInstance {
  return [RequestMessage_PersionSend defaultInstance];
}
- (RequestMessage_PersionSend*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RequestMessage_PersionSend*) buildPartial {
  RequestMessage_PersionSend* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (RequestMessage_PersionSend_Builder*) mergeFrom:(RequestMessage_PersionSend*) other {
  if (other == [RequestMessage_PersionSend defaultInstance]) {
    return self;
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  if (other.hasUserName) {
    [self setUserName:other.userName];
  }
  if (other.hasUserAvatar) {
    [self setUserAvatar:other.userAvatar];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RequestMessage_PersionSend_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RequestMessage_PersionSend_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setUserId:[input readInt32]];
        break;
      }
      case 18: {
        [self setUserName:[input readString]];
        break;
      }
      case 26: {
        [self setUserAvatar:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasUserId {
  return result.hasUserId;
}
- (int32_t) userId {
  return result.userId;
}
- (RequestMessage_PersionSend_Builder*) setUserId:(int32_t) value {
  result.hasUserId = YES;
  result.userId = value;
  return self;
}
- (RequestMessage_PersionSend_Builder*) clearUserId {
  result.hasUserId = NO;
  result.userId = 0;
  return self;
}
- (BOOL) hasUserName {
  return result.hasUserName;
}
- (NSString*) userName {
  return result.userName;
}
- (RequestMessage_PersionSend_Builder*) setUserName:(NSString*) value {
  result.hasUserName = YES;
  result.userName = value;
  return self;
}
- (RequestMessage_PersionSend_Builder*) clearUserName {
  result.hasUserName = NO;
  result.userName = @"";
  return self;
}
- (BOOL) hasUserAvatar {
  return result.hasUserAvatar;
}
- (NSData*) userAvatar {
  return result.userAvatar;
}
- (RequestMessage_PersionSend_Builder*) setUserAvatar:(NSData*) value {
  result.hasUserAvatar = YES;
  result.userAvatar = value;
  return self;
}
- (RequestMessage_PersionSend_Builder*) clearUserAvatar {
  result.hasUserAvatar = NO;
  result.userAvatar = [NSData data];
  return self;
}
@end

@interface RequestMessage_Builder()
@property (retain) RequestMessage* result;
@end

@implementation RequestMessage_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[RequestMessage alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (RequestMessage_Builder*) clear {
  self.result = [[[RequestMessage alloc] init] autorelease];
  return self;
}
- (RequestMessage_Builder*) clone {
  return [RequestMessage builderWithPrototype:result];
}
- (RequestMessage*) defaultInstance {
  return [RequestMessage defaultInstance];
}
- (RequestMessage*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RequestMessage*) buildPartial {
  RequestMessage* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (RequestMessage_Builder*) mergeFrom:(RequestMessage*) other {
  if (other == [RequestMessage defaultInstance]) {
    return self;
  }
  if (other.hasContent) {
    [self setContent:other.content];
  }
  if (other.hasPerReceipt) {
    [self mergePerReceipt:other.perReceipt];
  }
  if (other.hasPerSend) {
    [self mergePerSend:other.perSend];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RequestMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RequestMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setContent:[input readString]];
        break;
      }
      case 18: {
        RequestMessage_PersionReceipt_Builder* subBuilder = [RequestMessage_PersionReceipt builder];
        if (self.hasPerReceipt) {
          [subBuilder mergeFrom:self.perReceipt];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setPerReceipt:[subBuilder buildPartial]];
        break;
      }
      case 26: {
        RequestMessage_PersionSend_Builder* subBuilder = [RequestMessage_PersionSend builder];
        if (self.hasPerSend) {
          [subBuilder mergeFrom:self.perSend];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setPerSend:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasContent {
  return result.hasContent;
}
- (NSString*) content {
  return result.content;
}
- (RequestMessage_Builder*) setContent:(NSString*) value {
  result.hasContent = YES;
  result.content = value;
  return self;
}
- (RequestMessage_Builder*) clearContent {
  result.hasContent = NO;
  result.content = @"";
  return self;
}
- (BOOL) hasPerReceipt {
  return result.hasPerReceipt;
}
- (RequestMessage_PersionReceipt*) perReceipt {
  return result.perReceipt;
}
- (RequestMessage_Builder*) setPerReceipt:(RequestMessage_PersionReceipt*) value {
  result.hasPerReceipt = YES;
  result.perReceipt = value;
  return self;
}
- (RequestMessage_Builder*) setPerReceiptBuilder:(RequestMessage_PersionReceipt_Builder*) builderForValue {
  return [self setPerReceipt:[builderForValue build]];
}
- (RequestMessage_Builder*) mergePerReceipt:(RequestMessage_PersionReceipt*) value {
  if (result.hasPerReceipt &&
      result.perReceipt != [RequestMessage_PersionReceipt defaultInstance]) {
    result.perReceipt =
      [[[RequestMessage_PersionReceipt builderWithPrototype:result.perReceipt] mergeFrom:value] buildPartial];
  } else {
    result.perReceipt = value;
  }
  result.hasPerReceipt = YES;
  return self;
}
- (RequestMessage_Builder*) clearPerReceipt {
  result.hasPerReceipt = NO;
  result.perReceipt = [RequestMessage_PersionReceipt defaultInstance];
  return self;
}
- (BOOL) hasPerSend {
  return result.hasPerSend;
}
- (RequestMessage_PersionSend*) perSend {
  return result.perSend;
}
- (RequestMessage_Builder*) setPerSend:(RequestMessage_PersionSend*) value {
  result.hasPerSend = YES;
  result.perSend = value;
  return self;
}
- (RequestMessage_Builder*) setPerSendBuilder:(RequestMessage_PersionSend_Builder*) builderForValue {
  return [self setPerSend:[builderForValue build]];
}
- (RequestMessage_Builder*) mergePerSend:(RequestMessage_PersionSend*) value {
  if (result.hasPerSend &&
      result.perSend != [RequestMessage_PersionSend defaultInstance]) {
    result.perSend =
      [[[RequestMessage_PersionSend builderWithPrototype:result.perSend] mergeFrom:value] buildPartial];
  } else {
    result.perSend = value;
  }
  result.hasPerSend = YES;
  return self;
}
- (RequestMessage_Builder*) clearPerSend {
  result.hasPerSend = NO;
  result.perSend = [RequestMessage_PersionSend defaultInstance];
  return self;
}
@end

