// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class PersionReceive;
@class PersionReceive_Builder;
@class PersionSend;
@class PersionSend_Builder;
@class ResponseMessage;
@class ResponseMessage_Builder;
@class ResponseMessage_ContentMessage;
@class ResponseMessage_ContentMessage_Builder;
@class ResponseMessage_StatusResponse;
@class ResponseMessage_StatusResponse_Builder;

@interface MessageResposeRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ResponseMessage : PBExtendableMessage {
@private
  BOOL hasContent_:1;
  ResponseMessage_ContentMessage* content;
  NSMutableArray* mutableStatusList;
}
- (BOOL) hasContent;
@property (readonly, retain) ResponseMessage_ContentMessage* content;
- (NSArray*) statusList;
- (ResponseMessage_StatusResponse*) statusAtIndex:(int32_t) index;

+ (ResponseMessage*) defaultInstance;
- (ResponseMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResponseMessage_Builder*) builder;
+ (ResponseMessage_Builder*) builder;
+ (ResponseMessage_Builder*) builderWithPrototype:(ResponseMessage*) prototype;

+ (ResponseMessage*) parseFromData:(NSData*) data;
+ (ResponseMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ResponseMessage*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ResponseMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResponseMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResponseMessage_StatusResponse : PBGeneratedMessage {
@private
  BOOL hasErrorCode_:1;
  BOOL hasStatus_:1;
  int32_t errorCode;
  NSString* status;
}
- (BOOL) hasStatus;
- (BOOL) hasErrorCode;
@property (readonly, retain) NSString* status;
@property (readonly) int32_t errorCode;

+ (ResponseMessage_StatusResponse*) defaultInstance;
- (ResponseMessage_StatusResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResponseMessage_StatusResponse_Builder*) builder;
+ (ResponseMessage_StatusResponse_Builder*) builder;
+ (ResponseMessage_StatusResponse_Builder*) builderWithPrototype:(ResponseMessage_StatusResponse*) prototype;

+ (ResponseMessage_StatusResponse*) parseFromData:(NSData*) data;
+ (ResponseMessage_StatusResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseMessage_StatusResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ResponseMessage_StatusResponse*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ResponseMessage_StatusResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseMessage_StatusResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResponseMessage_StatusResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResponseMessage_StatusResponse_Builder : PBGeneratedMessage_Builder {
@private
  ResponseMessage_StatusResponse* result;
}

- (ResponseMessage_StatusResponse*) defaultInstance;

- (ResponseMessage_StatusResponse_Builder*) clear;
- (ResponseMessage_StatusResponse_Builder*) clone;

- (ResponseMessage_StatusResponse*) build;
- (ResponseMessage_StatusResponse*) buildPartial;

- (ResponseMessage_StatusResponse_Builder*) mergeFrom:(ResponseMessage_StatusResponse*) other;
- (ResponseMessage_StatusResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResponseMessage_StatusResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (NSString*) status;
- (ResponseMessage_StatusResponse_Builder*) setStatus:(NSString*) value;
- (ResponseMessage_StatusResponse_Builder*) clearStatus;

- (BOOL) hasErrorCode;
- (int32_t) errorCode;
- (ResponseMessage_StatusResponse_Builder*) setErrorCode:(int32_t) value;
- (ResponseMessage_StatusResponse_Builder*) clearErrorCode;
@end

@interface ResponseMessage_ContentMessage : PBGeneratedMessage {
@private
  BOOL hasMessageId_:1;
  BOOL hasTimeCreate_:1;
  BOOL hasContent_:1;
  int64_t messageId;
  NSString* timeCreate;
  NSString* content;
}
- (BOOL) hasMessageId;
- (BOOL) hasTimeCreate;
- (BOOL) hasContent;
@property (readonly) int64_t messageId;
@property (readonly, retain) NSString* timeCreate;
@property (readonly, retain) NSString* content;

+ (ResponseMessage_ContentMessage*) defaultInstance;
- (ResponseMessage_ContentMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResponseMessage_ContentMessage_Builder*) builder;
+ (ResponseMessage_ContentMessage_Builder*) builder;
+ (ResponseMessage_ContentMessage_Builder*) builderWithPrototype:(ResponseMessage_ContentMessage*) prototype;

+ (ResponseMessage_ContentMessage*) parseFromData:(NSData*) data;
+ (ResponseMessage_ContentMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseMessage_ContentMessage*) parseFromInputStream:(NSInputStream*) input;
+ (ResponseMessage_ContentMessage*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ResponseMessage_ContentMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResponseMessage_ContentMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResponseMessage_ContentMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResponseMessage_ContentMessage_Builder : PBGeneratedMessage_Builder {
@private
  ResponseMessage_ContentMessage* result;
}

- (ResponseMessage_ContentMessage*) defaultInstance;

- (ResponseMessage_ContentMessage_Builder*) clear;
- (ResponseMessage_ContentMessage_Builder*) clone;

- (ResponseMessage_ContentMessage*) build;
- (ResponseMessage_ContentMessage*) buildPartial;

- (ResponseMessage_ContentMessage_Builder*) mergeFrom:(ResponseMessage_ContentMessage*) other;
- (ResponseMessage_ContentMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResponseMessage_ContentMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMessageId;
- (int64_t) messageId;
- (ResponseMessage_ContentMessage_Builder*) setMessageId:(int64_t) value;
- (ResponseMessage_ContentMessage_Builder*) clearMessageId;

- (BOOL) hasTimeCreate;
- (NSString*) timeCreate;
- (ResponseMessage_ContentMessage_Builder*) setTimeCreate:(NSString*) value;
- (ResponseMessage_ContentMessage_Builder*) clearTimeCreate;

- (BOOL) hasContent;
- (NSString*) content;
- (ResponseMessage_ContentMessage_Builder*) setContent:(NSString*) value;
- (ResponseMessage_ContentMessage_Builder*) clearContent;
@end

@interface ResponseMessage_Builder : PBExtendableMessage_Builder {
@private
  ResponseMessage* result;
}

- (ResponseMessage*) defaultInstance;

- (ResponseMessage_Builder*) clear;
- (ResponseMessage_Builder*) clone;

- (ResponseMessage*) build;
- (ResponseMessage*) buildPartial;

- (ResponseMessage_Builder*) mergeFrom:(ResponseMessage*) other;
- (ResponseMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResponseMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) statusList;
- (ResponseMessage_StatusResponse*) statusAtIndex:(int32_t) index;
- (ResponseMessage_Builder*) replaceStatusAtIndex:(int32_t) index with:(ResponseMessage_StatusResponse*) value;
- (ResponseMessage_Builder*) addStatus:(ResponseMessage_StatusResponse*) value;
- (ResponseMessage_Builder*) addAllStatus:(NSArray*) values;
- (ResponseMessage_Builder*) clearStatusList;

- (BOOL) hasContent;
- (ResponseMessage_ContentMessage*) content;
- (ResponseMessage_Builder*) setContent:(ResponseMessage_ContentMessage*) value;
- (ResponseMessage_Builder*) setContentBuilder:(ResponseMessage_ContentMessage_Builder*) builderForValue;
- (ResponseMessage_Builder*) mergeContent:(ResponseMessage_ContentMessage*) value;
- (ResponseMessage_Builder*) clearContent;
@end

@interface PersionSend : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasUserName_:1;
  BOOL hasUserAvatar_:1;
  int32_t userId;
  NSString* userName;
  NSData* userAvatar;
}
- (BOOL) hasUserId;
- (BOOL) hasUserName;
- (BOOL) hasUserAvatar;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* userName;
@property (readonly, retain) NSData* userAvatar;

+ (PersionSend*) defaultInstance;
- (PersionSend*) defaultInstance;

+ (id<PBExtensionField>) persionSend;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PersionSend_Builder*) builder;
+ (PersionSend_Builder*) builder;
+ (PersionSend_Builder*) builderWithPrototype:(PersionSend*) prototype;

+ (PersionSend*) parseFromData:(NSData*) data;
+ (PersionSend*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PersionSend*) parseFromInputStream:(NSInputStream*) input;
+ (PersionSend*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (PersionSend*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PersionSend*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PersionSend*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PersionSend_Builder : PBGeneratedMessage_Builder {
@private
  PersionSend* result;
}

- (PersionSend*) defaultInstance;

- (PersionSend_Builder*) clear;
- (PersionSend_Builder*) clone;

- (PersionSend*) build;
- (PersionSend*) buildPartial;

- (PersionSend_Builder*) mergeFrom:(PersionSend*) other;
- (PersionSend_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PersionSend_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (PersionSend_Builder*) setUserId:(int32_t) value;
- (PersionSend_Builder*) clearUserId;

- (BOOL) hasUserName;
- (NSString*) userName;
- (PersionSend_Builder*) setUserName:(NSString*) value;
- (PersionSend_Builder*) clearUserName;

- (BOOL) hasUserAvatar;
- (NSData*) userAvatar;
- (PersionSend_Builder*) setUserAvatar:(NSData*) value;
- (PersionSend_Builder*) clearUserAvatar;
@end

@interface PersionReceive : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasUserName_:1;
  BOOL hasUserAvatar_:1;
  int32_t userId;
  NSString* userName;
  NSData* userAvatar;
}
- (BOOL) hasUserId;
- (BOOL) hasUserName;
- (BOOL) hasUserAvatar;
@property (readonly) int32_t userId;
@property (readonly, retain) NSString* userName;
@property (readonly, retain) NSData* userAvatar;

+ (PersionReceive*) defaultInstance;
- (PersionReceive*) defaultInstance;

+ (id<PBExtensionField>) persionReceive;
- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PersionReceive_Builder*) builder;
+ (PersionReceive_Builder*) builder;
+ (PersionReceive_Builder*) builderWithPrototype:(PersionReceive*) prototype;

+ (PersionReceive*) parseFromData:(NSData*) data;
+ (PersionReceive*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PersionReceive*) parseFromInputStream:(NSInputStream*) input;
+ (PersionReceive*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (PersionReceive*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PersionReceive*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PersionReceive*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PersionReceive_Builder : PBGeneratedMessage_Builder {
@private
  PersionReceive* result;
}

- (PersionReceive*) defaultInstance;

- (PersionReceive_Builder*) clear;
- (PersionReceive_Builder*) clone;

- (PersionReceive*) build;
- (PersionReceive*) buildPartial;

- (PersionReceive_Builder*) mergeFrom:(PersionReceive*) other;
- (PersionReceive_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PersionReceive_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int32_t) userId;
- (PersionReceive_Builder*) setUserId:(int32_t) value;
- (PersionReceive_Builder*) clearUserId;

- (BOOL) hasUserName;
- (NSString*) userName;
- (PersionReceive_Builder*) setUserName:(NSString*) value;
- (PersionReceive_Builder*) clearUserName;

- (BOOL) hasUserAvatar;
- (NSData*) userAvatar;
- (PersionReceive_Builder*) setUserAvatar:(NSData*) value;
- (PersionReceive_Builder*) clearUserAvatar;
@end

