// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class UsersMessage;
@class UsersMessage_Builder;

@interface UsersMessageRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface UsersMessage : PBGeneratedMessage {
@private
  BOOL hasUserId_:1;
  BOOL hasUserName_:1;
  int64_t userId;
  NSString* userName;
}
- (BOOL) hasUserId;
- (BOOL) hasUserName;
@property (readonly) int64_t userId;
@property (readonly, retain) NSString* userName;

+ (UsersMessage*) defaultInstance;
- (UsersMessage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UsersMessage_Builder*) builder;
+ (UsersMessage_Builder*) builder;
+ (UsersMessage_Builder*) builderWithPrototype:(UsersMessage*) prototype;

+ (UsersMessage*) parseFromData:(NSData*) data;
+ (UsersMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UsersMessage*) parseFromInputStream:(NSInputStream*) input;
+ (UsersMessage*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (UsersMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UsersMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UsersMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UsersMessage_Builder : PBGeneratedMessage_Builder {
@private
  UsersMessage* result;
}

- (UsersMessage*) defaultInstance;

- (UsersMessage_Builder*) clear;
- (UsersMessage_Builder*) clone;

- (UsersMessage*) build;
- (UsersMessage*) buildPartial;

- (UsersMessage_Builder*) mergeFrom:(UsersMessage*) other;
- (UsersMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UsersMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserId;
- (int64_t) userId;
- (UsersMessage_Builder*) setUserId:(int64_t) value;
- (UsersMessage_Builder*) clearUserId;

- (BOOL) hasUserName;
- (NSString*) userName;
- (UsersMessage_Builder*) setUserName:(NSString*) value;
- (UsersMessage_Builder*) clearUserName;
@end

