// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "UsersMessage.pb.h"

@implementation UsersMessageRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [UsersMessageRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface UsersMessage ()
@property int64_t userId;
@property (retain) NSString* userName;
@end

@implementation UsersMessage

- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) value {
  hasUserId_ = !!value;
}
@synthesize userId;
- (BOOL) hasUserName {
  return !!hasUserName_;
}
- (void) setHasUserName:(BOOL) value {
  hasUserName_ = !!value;
}
@synthesize userName;
- (void) dealloc {
  self.userName = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.userId = 0L;
    self.userName = @"";
  }
  return self;
}
static UsersMessage* defaultUsersMessageInstance = nil;
+ (void) initialize {
  if (self == [UsersMessage class]) {
    defaultUsersMessageInstance = [[UsersMessage alloc] init];
  }
}
+ (UsersMessage*) defaultInstance {
  return defaultUsersMessageInstance;
}
- (UsersMessage*) defaultInstance {
  return defaultUsersMessageInstance;
}
- (BOOL) isInitialized {
  if (!self.hasUserId) {
    return NO;
  }
  if (!self.hasUserName) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasUserId) {
    [output writeInt64:1 value:self.userId];
  }
  if (self.hasUserName) {
    [output writeString:2 value:self.userName];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasUserId) {
    size += computeInt64Size(1, self.userId);
  }
  if (self.hasUserName) {
    size += computeStringSize(2, self.userName);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (UsersMessage*) parseFromData:(NSData*) data {
  return (UsersMessage*)[[[UsersMessage builder] mergeFromData:data] build];
}
+ (UsersMessage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UsersMessage*)[[[UsersMessage builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (UsersMessage*) parseFromInputStream:(NSInputStream*) input {
  return (UsersMessage*)[[[UsersMessage builder] mergeFromInputStream:input] build];
}
+ (UsersMessage*) parseDelimitedFromInputStream:(NSInputStream*) input {
  return (UsersMessage*)[[[UsersMessage builder] mergeDelimitedFromInputStream:input] build];
}
+ (UsersMessage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UsersMessage*)[[[UsersMessage builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UsersMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (UsersMessage*)[[[UsersMessage builder] mergeFromCodedInputStream:input] build];
}
+ (UsersMessage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UsersMessage*)[[[UsersMessage builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UsersMessage_Builder*) builder {
  return [[[UsersMessage_Builder alloc] init] autorelease];
}
+ (UsersMessage_Builder*) builderWithPrototype:(UsersMessage*) prototype {
  return [[UsersMessage builder] mergeFrom:prototype];
}
- (UsersMessage_Builder*) builder {
  return [UsersMessage builder];
}
@end

@interface UsersMessage_Builder()
@property (retain) UsersMessage* result;
@end

@implementation UsersMessage_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[UsersMessage alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (UsersMessage_Builder*) clear {
  self.result = [[[UsersMessage alloc] init] autorelease];
  return self;
}
- (UsersMessage_Builder*) clone {
  return [UsersMessage builderWithPrototype:result];
}
- (UsersMessage*) defaultInstance {
  return [UsersMessage defaultInstance];
}
- (UsersMessage*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (UsersMessage*) buildPartial {
  UsersMessage* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (UsersMessage_Builder*) mergeFrom:(UsersMessage*) other {
  if (other == [UsersMessage defaultInstance]) {
    return self;
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  if (other.hasUserName) {
    [self setUserName:other.userName];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (UsersMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (UsersMessage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setUserId:[input readInt64]];
        break;
      }
      case 18: {
        [self setUserName:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasUserId {
  return result.hasUserId;
}
- (int64_t) userId {
  return result.userId;
}
- (UsersMessage_Builder*) setUserId:(int64_t) value {
  result.hasUserId = YES;
  result.userId = value;
  return self;
}
- (UsersMessage_Builder*) clearUserId {
  result.hasUserId = NO;
  result.userId = 0L;
  return self;
}
- (BOOL) hasUserName {
  return result.hasUserName;
}
- (NSString*) userName {
  return result.userName;
}
- (UsersMessage_Builder*) setUserName:(NSString*) value {
  result.hasUserName = YES;
  result.userName = value;
  return self;
}
- (UsersMessage_Builder*) clearUserName {
  result.hasUserName = NO;
  result.userName = @"";
  return self;
}
@end

